config/routes.rb
# == Route Map
#
#                    Prefix Verb   URI Pattern                                                                              Controller#Action
#          new_user_session GET    /users/sign_in(.:format)                                                                 devise/sessions#new
#              user_session POST   /users/sign_in(.:format)                                                                 devise/sessions#create
#      destroy_user_session DELETE /users/sign_out(.:format)                                                                devise/sessions#destroy
#         new_user_password GET    /users/password/new(.:format)                                                            devise/passwords#new
#        edit_user_password GET    /users/password/edit(.:format)                                                           devise/passwords#edit
#             user_password PATCH  /users/password(.:format)                                                                devise/passwords#update
#                           PUT    /users/password(.:format)                                                                devise/passwords#update
#                           POST   /users/password(.:format)                                                                devise/passwords#create
#  cancel_user_registration GET    /users/cancel(.:format)                                                                  devise/registrations#cancel
#     new_user_registration GET    /users/sign_up(.:format)                                                                 devise/registrations#new
#    edit_user_registration GET    /users/edit(.:format)                                                                    devise/registrations#edit
#         user_registration PATCH  /users(.:format)                                                                         devise/registrations#update
#                           PUT    /users(.:format)                                                                         devise/registrations#update
#                           DELETE /users(.:format)                                                                         devise/registrations#destroy
#                           POST   /users(.:format)                                                                         devise/registrations#create
#                     posts GET    /posts(.:format)                                                                         posts#index
#                           POST   /posts(.:format)                                                                         posts#create
#                  new_post GET    /posts/new(.:format)                                                                     posts#new
#                 edit_post GET    /posts/:id/edit(.:format)                                                                posts#edit
#                      post GET    /posts/:id(.:format)                                                                     posts#show
#                           PATCH  /posts/:id(.:format)                                                                     posts#update
#                           PUT    /posts/:id(.:format)                                                                     posts#update
#                           DELETE /posts/:id(.:format)                                                                     posts#destroy
#                      root GET    /                                                                                        posts#index
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do

  resources :categories
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts

  root "notes#index"
  get "/notes", to: "notes#index"
  get "/notes/:id", to: "notes#show"


  get "/authors", to: "authors#index"
  get "/authors/:id", to: "authors#show"
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :posts
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @category.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h4>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="page-header">
  <%= link_to categories_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @category, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing category</h1>
</div>

<%= render 'form' %>

app/views/categories/index.html.erb
<div class="page-header">
  <%= link_to new_category_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Category
  <% end %>
  <h1>Listing categories</h1>
  
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @categories) do |category| %>
            <td><%= category.name %></td>
            <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

<div class="one-blog">
  <h1 class="text-center">All Categories</h1>
  <div class="container">
  <div class="row">
    <div class="col col-xs-12">
      <div class="blog-grids">

        <% @categories.each do |p|%>
        <a href="/categories/<%= p.id %>">
          <div class="grid">
         
            <div class="entry-body">
              <h3><%= p.name %></h3>
              <div class="read-more-date">
                <a href="/categories/<%= p.id %>"> <%= p.posts.count %> posts</a>
              </div>
            </div>
          </div>
          </a>
        <% end %>

       
       
      </div>
    </div>
  </div>
</div>

</div>

app/views/categories/new.html.erb
<div class="page-header">
  <%= link_to categories_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New category</h1>
</div>

<%= render 'form' %>

app/views/categories/show.html.erb
  <div class="page-header">
    <%= link_to categories_path, class: 'btn btn-default' do %>
      <span class="glyphicon glyphicon-list-alt"></span>
      Back
    <% end %>
    <%= link_to edit_category_path(@category), class: 'btn btn-primary' do %>
      <span class="glyphicon glyphicon-pencil"></span>
      Edit
    <% end %>
    <h1>Show category</h1>
  </div>

  <dl class="dl-horizontal">
    <dt>Name:</dt>
    <dd><%= @category.name %></dd>

  </dl>

  <div class="row">
    <div class="col col-xs-12">
      <div class="blog-grids">

        <% @category.posts.each do |p|%>
        <a href="/notes/<%= p.id %>">
          <div class="grid">
            <div class="entry-media">
               <%= image_tag p.image.url(:medium) %>
            </div>
            <div class="entry-body">
              <span class="cat"><%= p.user.name %></span>
              <h3><a href="#"><%= p.title %></a></h3>
              <p><%= p.body[0..90] ... %></p>
              <div class="read-more-date">
                <a href="/notes/<%= p.id %>">Read More..</a>
                <span class="date"><%= time_ago_in_words(p.created_at)%></span>
              </div>
            </div>
          </div>
          </a>
        <% end %>

       
       
      </div>
    </div>
  </div>